### ISSUE TITLE
Omission of `openid` scope causes strategy to fail.

### ISSUE THREAD

**Issue by gavinballard** [abeland/omniauth-quickbooks-oauth2#1]
This may just be something that requires a documentation change, but the omission of `openid` in the list of requested scopes means that the fetching of OpenID information in the `raw_info` method fails with an authorization error when calling `access_token.get("https://#{accounts_domain}/v1/openid_connect/userinfo")`.

**Comment by abeland** [comment]
@gavinballard, thanks for pointing this out!

It's true, there is an implicit assumption there.
I have seen some omniauth strategies add the `openid` scope even when the caller doesn't explicitly list it, and seen some that just let the failure happen.

I'll think about this a bit more, but I see three possible solutions:

1. Always append `openid` to the scope list no matter what the client listed -- I don't like this because it doesn't trust the client and feels paternalistic
2. Don't try to fetch the additional info when `openid` is not in the scope list, and make this behavior clear in the README
3. Add a parameter to the strategy (something like `fetch_openid_info`, defaulting to `true`) that will raise an error unless `openid` was in the scope list -- this feels like the clearest and least ambiguous approach that still gives full control to the client

I don't like (1), but could see arguments for (2) or (3). I'm leaning towards (3). I'll bump the version once I implement (3).

**Comment by abeland** [comment]
Actually I started to implement (3) and then ran into this nifty warning from Intuit:

```
We're sorry!
The openid scope is required when the profile, email, phone, or address scopes are requested. Find out more about scopes here.
```

So I think it will suffice to just point this out in the docs more clearly.

**Comment by gavinballard** [comment]
Hey @abeland, thanks for your quick and thorough response! Looks like the commit you've put together would address the issue I was running into, although I think updated docs would be useful as well. Thanks!

**Comment by abeland** [comment]
Documentation and version bumped.
